export { default as EditorSkeleton } from './EditorSkeleton'
export { default as NavigationSkeleton } from './NavigationSkeleton'
export { default as DataAnalysisSkeleton } from './DataAnalysisSkeleton'
export { default as ChartSkeleton } from './ChartSkeleton'
export { default as ChatSkeleton } from './ChatSkeleton'
export { default as SettingsSkeleton } from './SettingsSkeleton'
export { default as MindMapSkeleton } from './MindMapSkeleton'
export { default as ListSkeleton } from './ListSkeleton'

import './skeleton.css'
